[package]
name = "carp"
version = "1.2.0"
edition = "2021"
authors = ["Andrea Sgobbi"]

[profile.release]
opt-level = 3
debug = false
rpath = false
debug-assertions = false
codegen-units = 1
lto = true
panic = "abort"